package jp.neonward;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.network.chat.Component;

public class GarageScreen extends Screen {
 int selected,l,t,w,h,page;boolean shop,requested;long cash;String message="読み込み中…";java.util.Set<String> owned=new java.util.HashSet<>();
 public GarageScreen(){super(Component.literal("NEON MOTOR"));}
 @Override public boolean isPauseScreen(){return false;}
 java.util.List<VehicleCatalog.Spec> visible(){var out=new java.util.ArrayList<VehicleCatalog.Spec>();for(var s:VehicleCatalog.ALL)if(shop?!CasinoGames.PRIZES.contains(s.id()):owned.contains(s.id()))out.add(s);return out;}
 void receive(com.google.gson.JsonObject o){shop=o.has("shop")&&o.get("shop").getAsBoolean();cash=o.has("cash")?o.get("cash").getAsLong():cash;owned.clear();var list=o.has("ownedVehicles")?o.getAsJsonArray("ownedVehicles"):o.getAsJsonArray("casinoVehicles");if(list!=null)for(var v:list)owned.add(v.getAsString());message=o.has("message")?o.get("message").getAsString():shop?"購入する車種を選んでください":"購入済みの車両だけ表示しています";selected=Math.min(selected,Math.max(0,visible().size()-1));rebuildWidgets();}
 @Override public void onClose(){minecraft.gui.setScreen(new PhoneScreen());}
 void command(String s){if(minecraft.player!=null)minecraft.player.connection.sendCommand("neongarage "+s);minecraft.gui.setScreen(null);}
 @Override protected void init(){w=Math.min(500,width-16);h=Math.min(380,height-12);l=(width-w)/2;t=(height-h)/2;var list=visible();int step=Math.min(24,(h-112)/8),left=Math.min(205,w/2-10);for(int i=0;i<8&&page*8+i<list.size();i++){final int n=page*8+i;var s=list.get(n);String label=s.name()+(shop?" / "+PhoneGarage.price(s.id())+" Cr":"");addRenderableWidget(new PhoneScreen.NeonButton(l+10,t+34+i*step,left,step-2,label,b->{selected=n;rebuildWidgets();}));}
  if(!list.isEmpty()){var s=list.get(Math.min(selected,list.size()-1));if(shop&&!owned.contains(s.id()))addRenderableWidget(new PhoneScreen.NeonButton(l+left+20,t+h-76,w-left-30,22,"購入 "+PhoneGarage.price(s.id())+" Cr",b->command("buy "+s.id())));else {addRenderableWidget(new PhoneScreen.NeonButton(l+left+20,t+h-76,w-left-30,22,"選んだ車両を呼ぶ",b->command(s.id())));addRenderableWidget(new PhoneScreen.NeonButton(l+10,t+h-77,left,18,"選んだ車種を改造",b->{if(minecraft.player!=null)minecraft.player.connection.sendCommand("neonmotor "+s.id()+" view");}));}}
  if(!shop)addRenderableWidget(new PhoneScreen.NeonButton(l+left+20,t+h-49,w-left-30,19,"近くの空の車両を回収",b->command("recall")));if(shop)addRenderableWidget(new PhoneScreen.NeonButton(l+10,t+h-49,left,19,"車種切替",b->{page=1-page;clearWidgets();init();}));addRenderableWidget(new PhoneScreen.NeonButton(l+10,t+h-25,w-20,18,"ホームに戻る",b->onClose()));if(!requested&&minecraft.player!=null){requested=true;minecraft.player.connection.sendCommand("neongarage view");}}
 @Override public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float delta){g.fill(l-4,t-4,l+w+4,t+h+4,0xff080c15);g.fill(l,t,l+w,t+h,0xff0b1926);g.outline(l,t,w,h,0xff4de7da);g.centeredText(font,shop?"NEON MOTOR / 車両購入":"NEON MOTOR / ガレージ",l+w/2,t+12,0xff64fff0);var list=visible();if(list.isEmpty())g.centeredText(font,shop?"購入する車種を選んでください":"購入済みの車両がありません",l+w/2,t+90,0xffffc875);else{var s=list.get(Math.min(selected,list.size()-1));int x=l+Math.min(205,w/2-10)+20,y=t+45;String[] lines={s.name(),s.style(),shop?"価格 "+PhoneGarage.price(s.id())+" Cr":"所有済み","最高速度 約"+Math.round(s.top()*72)+" km/h",s.seats()+"人乗り / 荷室 "+s.rows()*9+"枠",message};for(int i=0;i<lines.length;i++)g.text(font,lines[i],x,y+i*Math.min(18,Math.max(8,(h-127)/8)),i==0?0xfffd71b6:0xffbbdfeb);}g.text(font,"残高 "+cash+" Cr",l+12,t+h-43,0xffffd071);super.extractRenderState(g,mx,my,delta);}
}
