package jp.neonward;
/** Progress and rewards are server-owned; accepted quests retain their original rank. */
public final class GuildRanks {
 public static final String[] NAMES={"F","E","D","C","B","A","S"};
 static final int[] MULT={1,2,4,7,11,16,24},FIELD={8,12,0,0,0,0},TOWER={0,6,12,16,20,24},FLOOR={0,0,1,5,10,20};
 static int rank(MarketLedger.Account a){return Math.clamp(a.guildRank,0,6);}
 static int minimum(int q){return q==2?1:q==4?2:q==5?3:0;}
 static GuildCatalog.Quest quest(int q,int rank){if(rank<0)return GuildCatalog.QUESTS[q];int target=q==6?4+rank*2:q==0?5+rank*4:q<4?4+rank*3:q==4?8+rank*4:1+rank/3;int reward=new int[]{250,300,350,275,600,1400,200}[q]*MULT[rank];return new GuildCatalog.Quest(GuildCatalog.QUESTS[q].title(),target,reward,(q==6?"外域の薬草":q==0?"外域":q==1?"森林":q==2?"雪原":q==3?"荒野":q==4?"塔の敵":"塔のボス")+"を"+target+(q==6?"株採取":"体討伐")+((q==4||q==5)&&rank>=3?" / "+minFloor(rank)+"階以上":""));}
 static int minFloor(int rank){return rank<3?1:1+(rank-3)*5;}
 static GuildCatalog.Quest accepted(MarketLedger.Account a,int q){return quest(q,a.guildQuestRanks.getOrDefault(q,-1));}
 static String accept(MarketLedger.Account a,int q){if(rank(a)<minimum(q))return NAMES[minimum(q)]+"ランクから受注できます";if(a.guildQuests.containsKey(q))return "この依頼は受注済みです";if(a.guildQuests.size()>=3)return "同時受注は3件までです";a.guildQuests.put(q,0);a.guildQuestRanks.put(q,rank(a));return NAMES[rank(a)]+"ランク依頼を受注："+quest(q,rank(a)).title();}
 static String claim(MarketLedger.Account a,int q){var spec=accepted(a,q);if(a.guildQuests.getOrDefault(q,-1)<spec.target())return "目標を達成してから報告してね";a.cash=Math.addExact(a.cash,spec.reward());if(rank(a)<6&&a.guildQuestRanks.getOrDefault(q,-1)==rank(a))a.guildRankReports=Math.min(5,a.guildRankReports+1);a.guildQuests.remove(q);a.guildQuestRanks.remove(q);return "報告完了 / +"+spec.reward()+" Cr / "+(rank(a)==6?"再受注できます（回数無制限）":"昇級まで "+a.guildRankReports+"/5件");}
 static String exam(MarketLedger.Account a){int r=rank(a);if(r==6)return "最高ランクSです";if(a.guildExamActive)return description(a);if(a.guildRankReports<5)return "今のランクの依頼をあと"+(5-a.guildRankReports)+"件報告してください";a.guildExamActive=true;a.guildExamField=a.guildExamTower=a.guildExamBoss=0;return "昇級試験を開始 / "+description(a);}
 static String description(MarketLedger.Account a){int r=rank(a);if(r==6)return "最高ランクS / 依頼は回数無制限で再受注可能";return "試験：外域 "+a.guildExamField+"/"+FIELD[r]+" 塔 "+a.guildExamTower+"/"+TOWER[r]+(FLOOR[r]>0?" ボス"+FLOOR[r]+"階以上 "+a.guildExamBoss+"/1":"");}
 static boolean ready(MarketLedger.Account a){int r=rank(a);return r<6&&a.guildExamActive&&a.guildExamField>=FIELD[r]&&a.guildExamTower>=TOWER[r]&&(FLOOR[r]==0||a.guildExamBoss>=1);}
 static String promote(MarketLedger.Account a){if(!ready(a))return "試験の目標を達成してから合格報告してね";int bonus=1000*(rank(a)+1);a.cash=Math.addExact(a.cash,bonus);a.guildRank++;a.guildRankReports=0;a.guildExamActive=false;a.guildExamField=a.guildExamTower=a.guildExamBoss=0;return "昇級試験合格！ "+NAMES[rank(a)]+"ランク / 祝い金 +"+bonus+" Cr";}
 static boolean progress(MarketLedger.Account a,boolean wild,boolean dungeon,boolean boss,String habitat,int floor){boolean changed=false;for(int q:new java.util.ArrayList<>(a.guildQuests.keySet())){if(q<0||q>=GuildCatalog.QUESTS.length)continue;int r=a.guildQuestRanks.getOrDefault(q,-1);if((q==4||q==5)&&r>=3&&floor<minFloor(r))continue;if(GuildCatalog.matches(q,wild,dungeon,boss,habitat)){int n=a.guildQuests.get(q),goal=accepted(a,q).target();if(n<goal){a.guildQuests.put(q,n+1);changed=true;}}}int r=rank(a);if(a.guildExamActive&&r<6){if(wild&&a.guildExamField<FIELD[r]){a.guildExamField++;changed=true;}if(dungeon&&a.guildExamTower<TOWER[r]){a.guildExamTower++;changed=true;}if(dungeon&&boss&&floor>=FLOOR[r]&&FLOOR[r]>0&&a.guildExamBoss<1){a.guildExamBoss=1;changed=true;}}return changed;}
}
