package jp.neonward;
import net.minecraft.client.Minecraft;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.fabric.api.client.rendering.v1.hud.*;
public final class GunControls {
 static long nextShot;static net.minecraft.client.KeyMapping reloadKey;
 public static boolean holding(){var mc=Minecraft.getInstance();return mc.player!=null&&!mc.player.isSpectator()&&mc.gui.screen()==null&&!CameraScreen.active()&&!PhoneEquipment.isHeld(mc.player)&&NeonArsenal.isGun(mc.player.getItemInHand(NeonArsenal.gunHand(mc.player)));}
 public static boolean aiming(){var mc=Minecraft.getInstance();return holding()&&mc.player.isUsingItem()&&NeonArsenal.isGun(mc.player.getUseItem());}
 public static float zoom(){var mc=Minecraft.getInstance();return aiming()?(NeonArsenal.sniper(mc.player.getUseItem())?.35f:.8f):1;}
 public static void init(){
  reloadKey=net.fabricmc.fabric.api.client.keymapping.v1.KeyMappingHelper.registerKeyMapping(new net.minecraft.client.KeyMapping("key.neonward.reload",org.lwjgl.glfw.GLFW.GLFW_KEY_R,net.minecraft.client.KeyMapping.Category.register(NeonWard.id("guns"))));
  ClientTickEvents.START_CLIENT_TICK.register(mc->{boolean reload=false;while(reloadKey.consumeClick())reload=true;if(!holding()){nextShot=0;return;}if(reload)mc.player.connection.sendCommand("neongun reload");var gun=mc.player.getItemInHand(NeonArsenal.gunHand(mc.player));boolean click=false;while(mc.options.keyAttack.consumeClick())click=true;long now=System.currentTimeMillis();boolean wants=click||NeonArsenal.automatic(gun)&&mc.options.keyAttack.isDown();if(gun.is(NeonArsenal.ITEMS.get("cryo_projector")))wants=aiming()&&mc.options.keyAttack.isDown();if(wants&&!GunReload.reloading(gun)&&now>=nextShot&&!mc.player.getCooldowns().isOnCooldown(gun)){mc.player.connection.sendCommand("neongun fire");nextShot=now+(NeonArsenal.automatic(gun)?320:160);}});
  HudElementRegistry.attachElementBefore(VanillaHudElements.CHAT,NeonWard.id("gun_sights"),(g,d)->{if(!holding())return;var mc=Minecraft.getInstance();if(!mc.options.getCameraType().isFirstPerson())return;int x=g.guiWidth()/2,y=g.guiHeight()/2;var gun=mc.player.getItemInHand(NeonArsenal.gunHand(mc.player));boolean loading=GunReload.reloading(gun);String ammo=loading?"RELOADING / "+Math.max(0,(GunReload.until(gun)-System.currentTimeMillis()+99)/100)/10.0+"s":GunReload.remaining(gun)+" / "+GunReload.profile(gun).capacity()+"   弾薬 ∞";g.centeredText(mc.font,ammo,x,g.guiHeight()-85,loading?0xffffc36b:0xff7bffe4);g.centeredText(mc.font,reloadKey.getTranslatedKeyMessage().getString()+"：リロード",x,g.guiHeight()-74,0xffb4d9e0);if(loading){g.fill(x-48,g.guiHeight()-96,x+48,g.guiHeight()-92,0xff172b39);g.fill(x-48,g.guiHeight()-96,x-48+(int)(96*GunReload.progress(gun)),g.guiHeight()-92,0xffffc36b);}if(aiming()){g.fill(x-1,y-1,x+2,y+2,0xff64ffe8);if(NeonArsenal.sniper(mc.player.getUseItem())){g.fill(x-65,y,x-9,y+1,0xff70f2df);g.fill(x+9,y,x+66,y+1,0xff70f2df);g.fill(x,y-45,x+1,y-9,0xff70f2df);g.fill(x,y+9,x+1,y+46,0xff70f2df);for(int j=15;j<60;j+=15){g.fill(x+j,y-2,x+j+1,y+3,0xff70f2df);g.fill(x-j,y-2,x-j+1,y+3,0xff70f2df);}}}g.centeredText(mc.font,"右長押し：構える / 左："+(NeonArsenal.automatic(mc.player.getItemInHand(NeonArsenal.gunHand(mc.player)))?"連射":"発射"),x,g.guiHeight()-62,0xff7bdcd8);});
 }
}
