package jp.neonward;
import java.util.*;
/** 48-card, two-player koi-koi, twelve rounds, one koi-koi declaration per round. */
public final class KoiRound {
 public static final String[] MONTH={"松","梅","桜","藤","菖蒲","牡丹","萩","芒","菊","紅葉","柳","桐"};
 static final Set<Integer> LIGHT=Set.of(0,8,28,40,44),ANIMAL=Set.of(4,12,16,20,24,29,32,36,41),RIBBON=Set.of(1,5,9,13,17,21,25,33,37,42);
 static final Map<Integer,String> SPECIAL=Map.ofEntries(Map.entry(0,"鶴"),Map.entry(4,"鶯"),Map.entry(8,"幕"),Map.entry(12,"時鳥"),Map.entry(16,"八橋"),Map.entry(20,"蝶"),Map.entry(24,"猪"),Map.entry(28,"月"),Map.entry(29,"雁"),Map.entry(32,"盃"),Map.entry(36,"鹿"),Map.entry(40,"小野道風"),Map.entry(41,"燕"),Map.entry(44,"鳳凰"));
 public static String label(int c){return MONTH[c/4]+"・"+(SPECIAL.containsKey(c)?SPECIAL.get(c):RIBBON.contains(c)?"短冊":"カス");}
 public static class Seat {public String id="",name="空席";public boolean cpu;public int points;public List<Integer> hand=new ArrayList<>(),taken=new ArrayList<>();}
 public Seat[] seats={new Seat(),new Seat()};public List<Integer> deck=new ArrayList<>(),field=new ArrayList<>();public int round,dealer,turn,cursor,pending=-1,koier=-1,winner=-1;public int[] previous={0,0};public String phase="lobby",after="",message="着席して開始。空席はCPUです。";public long revision;public Set<Integer> ready=new HashSet<>();
 public int seat(String id){for(int i=0;i<2;i++)if(seats[i].id.equals(id))return i;return -1;}
 public int join(String id,String name){int i=seat(id);if(i>=0)return i;if(!phase.equals("lobby")&&!phase.equals("end"))throw new IllegalArgumentException("対局中です");for(i=0;i<2;i++)if(seats[i].id.isEmpty()||seats[i].cpu){seats[i]=new Seat();seats[i].id=id;seats[i].name=name;return i;}throw new IllegalArgumentException("満席です");}
 public void start(Random r){if(!phase.equals("lobby")&&!phase.equals("end"))throw new IllegalArgumentException("対局中です");for(int i=0;i<2;i++){if(seats[i].id.isEmpty()){seats[i].id="koi-cpu:"+i;seats[i].name="CPU 花織";seats[i].cpu=true;}seats[i].points=0;}round=0;dealer=r.nextInt(2);deal(r);}
 void deal(Random r){do{deck.clear();for(int i=0;i<48;i++)deck.add(i);Collections.shuffle(deck,r);cursor=0;field.clear();for(var s:seats){s.hand.clear();s.taken.clear();for(int i=0;i<8;i++)s.hand.add(deck.get(cursor++));}for(int i=0;i<8;i++)field.add(deck.get(cursor++));}while(four(field));previous=new int[2];koier=-1;winner=-1;pending=-1;ready.clear();turn=dealer;phase="play";message=(round+1)+"回戦 / "+seats[turn].name+"の番";for(int i=0;i<2;i++){int who=(dealer+i)%2;if(special(seats[who].hand)){finish(who,6,"手四・くっつき");break;}}revision++;}
 static boolean four(List<Integer> cards){int[] n=new int[12];for(int c:cards)n[c/4]++;return Arrays.stream(n).anyMatch(v->v==4);}
 static boolean special(List<Integer> h){int[] n=new int[12];for(int c:h)n[c/4]++;return Arrays.stream(n).anyMatch(v->v==4)||Arrays.stream(n).filter(v->v==2).count()==4;}
 static Map<String,Integer> yaku(List<Integer> cards){var c=new HashSet<>(cards);var out=new LinkedHashMap<String,Integer>();long light=c.stream().filter(LIGHT::contains).count();if(light==5)out.put("五光",10);else if(light==4)out.put(c.contains(40)?"雨四光":"四光",c.contains(40)?7:8);else if(light==3&&!c.contains(40))out.put("三光",5);if(c.containsAll(List.of(20,24,36)))out.put("猪鹿蝶",5);if(c.containsAll(List.of(1,5,9)))out.put("赤短",5);if(c.containsAll(List.of(21,33,37)))out.put("青短",5);if(c.containsAll(List.of(8,32)))out.put("花見酒",5);if(c.containsAll(List.of(28,32)))out.put("月見酒",5);int animals=(int)c.stream().filter(ANIMAL::contains).count(),ribbons=(int)c.stream().filter(RIBBON::contains).count(),junk=(int)c.stream().filter(v->!LIGHT.contains(v)&&!ANIMAL.contains(v)&&!RIBBON.contains(v)||v==32).count();if(animals>=5)out.put("タネ",animals-4);if(ribbons>=5)out.put("タン",ribbons-4);if(junk>=10)out.put("カス",junk-9);return out;}
 static int score(List<Integer> c){return yaku(c).values().stream().mapToInt(Integer::intValue).sum();}
 List<Integer> matches(int c){return field.stream().filter(v->v/4==c/4).toList();}
 void place(int card,String next){pending=card;after=next;var match=matches(card);if(match.size()==2){phase="match";message=label(card)+"：取る場札を選んでください";}else {if(match.isEmpty())field.add(card);else {seats[turn].taken.add(card);seats[turn].taken.addAll(match);field.removeAll(match);}pending=-1;advance();}}
 void advance(){if(after.equals("draw")){if(cursor>=deck.size()){evaluate();return;}int c=deck.get(cursor++);place(c,"score");}else evaluate();}
 void evaluate(){int value=score(seats[turn].taken);if(value>previous[turn]){previous[turn]=value;if(koier>=0){finish(turn,value,"出来役");return;}phase="decide";message=seats[turn].name+"：役ができました。勝負 / こいこい";return;}if(seats[0].hand.isEmpty()&&seats[1].hand.isEmpty()){if(koier>=0)finish(koier,score(seats[koier].taken),"手札終了");else {winner=-1;phase="result";message="引き分け / 役なし";ready.clear();}return;}turn=1-turn;phase="play";message=seats[turn].name+"の番";}
 void finish(int who,int base,String cause){int points=base>=7?base*2:base;if(koier>=0&&who!=koier)points*=2;seats[who].points+=points;winner=who;message=seats[who].name+"："+cause+" +"+points+"点 / "+String.join("・",yaku(seats[who].taken).keySet());phase="result";ready.clear();revision++;}
 public void action(int who,String action,int arg,Random r){if(who<0||who>1)throw new IllegalArgumentException("先に着席してください");if(action.equals("start")){start(r);return;}if(phase.equals("result")&&action.equals("next")){ready.add(who);nextIfReady(r);revision++;return;}if(who!=turn)throw new IllegalArgumentException("相手の番です");
  if(phase.equals("play")&&action.equals("play")){if(!seats[who].hand.remove(Integer.valueOf(arg)))throw new IllegalArgumentException("手札にありません");place(arg,"draw");}
  else if(phase.equals("match")&&action.equals("match")){if(!matches(pending).contains(arg))throw new IllegalArgumentException("同じ月の札を選んでください");seats[turn].taken.add(pending);seats[turn].taken.add(arg);field.remove(Integer.valueOf(arg));pending=-1;advance();}
  else if(phase.equals("decide")&&(action.equals("stop")||action.equals("koi"))){if(action.equals("stop"))finish(who,score(seats[who].taken),"勝負");else {koier=who;message=seats[who].name+"：こいこい！";if(seats[0].hand.isEmpty()&&seats[1].hand.isEmpty())finish(who,score(seats[who].taken),"手札終了");else {turn=1-turn;phase="play";}}}
  else throw new IllegalArgumentException("その操作はできません");revision++;
 }
 void nextIfReady(Random r){for(int i=0;i<2;i++)if(!seats[i].cpu&&!ready.contains(i))return;dealer=winner>=0?winner:1-dealer;if(++round==12){phase="end";message="12回戦終了 / "+seats[0].name+" "+seats[0].points+"点 / "+seats[1].name+" "+seats[1].points+"点";}else deal(r);}
 public boolean cpu(Random r,java.util.function.IntPredicate controlled){if(phase.equals("result")){for(int i=0;i<2;i++)if(controlled.test(i))ready.add(i);String old=phase;nextIfReady(r);return !old.equals(phase);}if(!controlled.test(turn))return false;if(phase.equals("play")){int best=seats[turn].hand.getFirst(),value=-1;for(int c:seats[turn].hand){int v=matches(c).isEmpty()?0:10;v+=LIGHT.contains(c)?4:ANIMAL.contains(c)?3:RIBBON.contains(c)?2:1;for(int m:matches(c))v+=LIGHT.contains(m)?5:ANIMAL.contains(m)?3:1;if(v>value){value=v;best=c;}}action(turn,"play",best,r);return true;}if(phase.equals("match")){int best=matches(pending).stream().max(Comparator.comparingInt(c->LIGHT.contains(c)?5:ANIMAL.contains(c)?3:RIBBON.contains(c)?2:1)).orElseThrow();action(turn,"match",best,r);return true;}if(phase.equals("decide")){action(turn,score(seats[turn].taken)>=7||seats[turn].hand.size()<3?"stop":"koi",0,r);return true;}return false;}
}
