package jp.neonward;
import java.util.*;
import org.mahjong4j.*;
import org.mahjong4j.hands.*;
import org.mahjong4j.tile.Tile;
/** Saved four-seat East-only game. Concealed hands are never included in a shared snapshot. */
public final class MahjongRound {
 public static class Meld {public String kind;public int tile,from;public boolean open;Meld(String k,int t,int f,boolean o){kind=k;tile=t;from=f;open=o;}}
 public static class Seat {public String id="",name="空席";public boolean cpu,reach,ippatsu,doubleReach,tempFuriten,reachFuriten;public int points=25000,drawn=-1;public List<Integer> hand=new ArrayList<>(),river=new ArrayList<>(),discardHistory=new ArrayList<>();public List<Meld> melds=new ArrayList<>();}
 public Seat[] seats={new Seat(),new Seat(),new Seat(),new Seat()};public String phase="lobby",message="着席して開始。空席はCPUが参加します。";
 public List<Integer> wall=new ArrayList<>();public int turn,dealer,round,honba,sticks,cursor,limit,kans,lastTile=-1,lastFrom=-1;public boolean rinshan,anyCall;public Map<Integer,String> claims=new HashMap<>();public Set<Integer> responders=new HashSet<>();public Set<Integer> ready=new HashSet<>();public int winner=-1;public long revision;
 public int seat(String id){for(int i=0;i<4;i++)if(seats[i].id.equals(id))return i;return -1;}
 public int join(String id,String name){int n=seat(id);if(n>=0)return n;if(!phase.equals("lobby")&&!phase.equals("end"))throw new IllegalArgumentException("対局中です。観戦できます");for(int i=0;i<4;i++)if(seats[i].id.isEmpty()||seats[i].cpu){seats[i]=new Seat();seats[i].id=id;seats[i].name=name;return i;}throw new IllegalArgumentException("満席です");}
 public void start(Random r){if(!phase.equals("lobby")&&!phase.equals("end"))throw new IllegalArgumentException("対局中です");for(int i=0;i<4;i++){if(seats[i].id.isEmpty()){seats[i].id="cpu:"+i;seats[i].name=new String[]{"CPU 蒼","CPU 蓮","CPU 凛","CPU 玄"}[i];seats[i].cpu=true;}seats[i].points=25000;}dealer=r.nextInt(4);round=honba=sticks=0;deal(r);}
 void deal(Random r){wall.clear();for(int t=0;t<34;t++)for(int n=0;n<4;n++)wall.add(t);Collections.shuffle(wall,r);cursor=0;limit=122;kans=0;anyCall=false;claims.clear();responders.clear();ready.clear();winner=-1;for(var s:seats){s.hand.clear();s.river.clear();s.discardHistory.clear();s.melds.clear();s.reach=s.ippatsu=s.doubleReach=s.tempFuriten=s.reachFuriten=false;s.drawn=-1;for(int j=0;j<13;j++)s.hand.add(wall.get(cursor++));Collections.sort(s.hand);}turn=dealer;phase="draw";draw(false);message="東"+(round+1)+"局 "+honba+"本場 / "+seats[turn].name+"の番";revision++;}
 void draw(boolean replacement){if(cursor>=limit&&!replacement){exhaust();return;}var s=seats[turn];s.tempFuriten=false;s.drawn=replacement?wall.get(136-kans):wall.get(cursor++);s.hand.add(s.drawn);rinshan=replacement;phase="draw";revision++;}
 public static String tile(int t){if(t<0)return "?";return t<27?(t%9+1)+new String[]{"萬","筒","索"}[t/9]:new String[]{"東","南","西","北","白","發","中"}[t-27];}
 static int dora(int t){return t<27?t/9*9+(t%9+1)%9:t<31?27+(t-27+1)%4:31+(t-31+1)%3;}
 List<Tile> doras(boolean ura){var out=new ArrayList<Tile>();for(int i=0;i<=kans;i++)out.add(Tile.valueOf(dora(wall.get(130-i*2+(ura?1:0)))));return out;}
 List<Mentsu> groups(Seat s)throws Exception{var out=new ArrayList<Mentsu>();for(var m:s.melds)out.add(m.kind.equals("chi")?new Shuntsu(true,Tile.valueOf(m.tile+1)):m.kind.equals("kan")?new Kantsu(m.open,Tile.valueOf(m.tile)):new Kotsu(true,Tile.valueOf(m.tile)));return out;}
 static int[] counts(List<Integer> tiles){int[] c=new int[34];for(int t:tiles)c[t]++;return c;}
 boolean shape(Seat s,int extra){try{var c=counts(s.hand);if(extra>=0)c[extra]++;if(Arrays.stream(c).anyMatch(n->n>4))return false;return new Hands(c,Tile.valueOf(extra>=0?extra:s.hand.getLast()),groups(s)).getCanWin();}catch(Exception e){return false;}}
 Set<Integer> waits(Seat s){var result=new HashSet<Integer>();for(int t=0;t<34;t++)if(shape(s,t))result.add(t);return result;}
 public record Win(int han,int fu,int base,String yaku){}
 Win score(int who,int tile,boolean tsumo){var s=seats[who];try{var c=counts(s.hand);if(!tsumo)c[tile]++;var h=new Hands(c,Tile.valueOf(tile),groups(s));if(!h.getCanWin())return null;var g=new GeneralSituation(!anyCall&&seats[who].river.isEmpty(),cursor>=limit,Tile.TON,doras(false),s.reach?doras(true):List.of());var p=new PersonalSituation(tsumo,s.ippatsu,s.reach,s.doubleReach,false,tsumo&&rinshan,Tile.valueOf(27+(who-dealer+4)%4));var calc=new org.mahjong4j.Player(h,g,p);calc.calculate();int yakuman=calc.getYakumanList().size();if(yakuman>0)return new Win(13*yakuman,0,8000*yakuman,String.join("・",calc.getYakumanList().stream().map(v->v.getJapanese()).toList()));if(calc.getHan()==0)return null;int han=calc.getHan(),fu=calc.getFu()==25?25:Math.max(30,((calc.getFu()+9)/10)*10);if(calc.getFu()==20&&tsumo)fu=20;int base=han>=13?8000:han>=11?6000:han>=8?4000:han>=6?3000:han>=5?2000:Math.min(2000,fu*(1<<(han+2)));return new Win(han,fu,base,String.join("・",calc.getNormalYakuList().stream().map(v->v.getJapanese()).toList()));}catch(Exception e){return null;}}
 boolean ron(int who){var s=seats[who];if(who==lastFrom||s.tempFuriten||s.reachFuriten||s.discardHistory.stream().anyMatch(waits(s)::contains))return false;return score(who,lastTile,false)!=null;}
 boolean closed(Seat s){return s.melds.stream().noneMatch(m->m.open);}
 List<String> options(int who){var out=new ArrayList<String>();if(phase.equals("claim")&&who!=lastFrom){var s=seats[who];if(ron(who))out.add("ron");if(!s.reach&&cursor<limit){int count=Collections.frequency(s.hand,lastTile);if(count>=2)out.add("pon");if(count>=3&&kans<4)out.add("kan");if(who==(lastFrom+1)%4&&lastTile<27)for(int low=Math.max(lastTile/9*9,lastTile-2);low<=Math.min(lastTile,lastTile/9*9+6);low++){var h=new ArrayList<>(s.hand);boolean ok=true;for(int t=low;t<low+3;t++)if(t!=lastTile&&!h.remove(Integer.valueOf(t)))ok=false;if(ok)out.add("chi:"+low);}}out.add("pass");}return out;}
 public void action(int who,String action,int arg,Random random){if(who<0||who>3)throw new IllegalArgumentException("先に着席してください");if(action.equals("start")){start(random);return;}if(phase.equals("result")){ready.add(who);if(allReady())next(random);revision++;return;}
  if(phase.equals("claim")){String cmd=action.equals("chi")?"chi:"+arg:action;if(!responders.contains(who)||claims.containsKey(who)||!options(who).contains(cmd))throw new IllegalArgumentException("その操作はできません");if(!cmd.equals("ron")&&ron(who)){seats[who].tempFuriten=true;if(seats[who].reach)seats[who].reachFuriten=true;}claims.put(who,cmd);revision++;resolve();return;}
  if(!phase.equals("draw")||turn!=who)throw new IllegalArgumentException("自分の番をお待ちください");var s=seats[who];
  if(action.equals("tsumo")){var win=score(who,s.drawn,true);if(s.drawn<0||win==null)throw new IllegalArgumentException("役のある和了形ではありません");win(who,true,win);return;}
  if(action.equals("ankan")){if(kans>=4||s.reach||cursor>=limit||Collections.frequency(s.hand,arg)!=4)throw new IllegalArgumentException("暗槓できません（リーチ後の槓なし）");for(int j=0;j<4;j++)s.hand.remove(Integer.valueOf(arg));s.melds.add(new Meld("kan",arg,who,false));onKan();return;}
  if(!action.equals("discard")&&!action.equals("reach"))throw new IllegalArgumentException("牌を選んで打牌してください");if(arg<0||arg>=s.hand.size())throw new IllegalArgumentException("牌がありません");int tile=s.hand.get(arg);if(s.reach&&arg!=s.hand.size()-1)throw new IllegalArgumentException("リーチ後はツモ切りです");if(action.equals("reach")){if(s.reach||!closed(s)||s.points<1000||limit-cursor<4)throw new IllegalArgumentException("リーチできません");s.hand.remove(arg);boolean tenpai=!waits(s).isEmpty();s.hand.add(arg,tile);if(!tenpai)throw new IllegalArgumentException("その打牌では聴牌しません");s.reach=true;s.doubleReach=s.river.isEmpty()&&!anyCall;s.ippatsu=true;s.points-=1000;sticks++;}else s.ippatsu=false;
  s.hand.remove(arg);Collections.sort(s.hand);s.river.add(tile);s.discardHistory.add(tile);s.drawn=-1;lastTile=tile;lastFrom=who;rinshan=false;phase="claim";claims.clear();responders.clear();for(int j=0;j<4;j++)if(j!=who&&options(j).size()>1)responders.add(j);message=seats[who].name+"："+tile(tile)+(action.equals("reach")?" リーチ！":"");revision++;resolve();
 }
 boolean allReady(){for(int i=0;i<4;i++)if(!seats[i].cpu&&!ready.contains(i))return false;return true;}
 void resolve(){if(!claims.keySet().containsAll(responders))return;for(int d=1;d<4;d++){int who=(lastFrom+d)%4;if("ron".equals(claims.get(who))){win(who,false,score(who,lastTile,false));return;}}
  int caller=-1;String call="";for(int d=1;d<4;d++){int i=(lastFrom+d)%4;String c=claims.getOrDefault(i,"");if(c.equals("pon")||c.equals("kan")){caller=i;call=c;break;}}if(caller<0){int next=(lastFrom+1)%4;String c=claims.getOrDefault(next,"");if(c.startsWith("chi:")){caller=next;call=c;}}
  if(caller>=0){turn=caller;var s=seats[caller];int tile=lastTile;seats[lastFrom].river.removeLast();if(call.startsWith("chi:")){int low=Integer.parseInt(call.substring(4));for(int t=low;t<low+3;t++)if(t!=tile)s.hand.remove(Integer.valueOf(t));s.melds.add(new Meld("chi",low,lastFrom,true));}else {int n=call.equals("kan")?3:2;for(int i=0;i<n;i++)s.hand.remove(Integer.valueOf(tile));s.melds.add(new Meld(call,tile,lastFrom,true));}anyCall=true;for(var player:seats)player.ippatsu=false;s.drawn=-1;phase="draw";if(call.equals("kan"))onKan();message=s.name+"："+call;revision++;return;}
  turn=(lastFrom+1)%4;draw(false);
 }
 void onKan(){kans++;limit--;anyCall=true;for(var s:seats)s.ippatsu=false;draw(true);}
 static int ceil100(int n){return (n+99)/100*100;}
 void win(int who,boolean tsumo,Win win){if(win==null)throw new IllegalArgumentException("和了できません");int gained=0;if(tsumo){for(int i=0;i<4;i++)if(i!=who){int pay=ceil100(win.base*(who==dealer||i==dealer?2:1))+honba*100;seats[i].points-=pay;gained+=pay;}}else {gained=ceil100(win.base*(who==dealer?6:4))+honba*300;seats[lastFrom].points-=gained;}seats[who].points+=gained+sticks*1000;sticks=0;winner=who;message=seats[who].name+(tsumo?" ツモ！ ":" ロン！ ")+win.yaku+" "+win.han+"翻 "+win.fu+"符 / +"+gained;phase="result";ready.clear();revision++;}
 void exhaust(){var tenpai=new ArrayList<Integer>();for(int i=0;i<4;i++)if(!waits(seats[i]).isEmpty())tenpai.add(i);if(!tenpai.isEmpty()&&tenpai.size()<4)for(int i=0;i<4;i++)seats[i].points+=tenpai.contains(i)?3000/tenpai.size():-3000/(4-tenpai.size());winner=tenpai.contains(dealer)?dealer:-1;message="流局 / 聴牌 "+tenpai.size()+"人";phase="result";ready.clear();revision++;}
 void next(Random r){boolean draw=message.startsWith("流局"),repeat=winner==dealer;if(draw||repeat)honba++;else honba=0;if(!repeat){round++;dealer=(dealer+1)%4;}if(round>=4||Arrays.stream(seats).anyMatch(s->s.points<0)){phase="end";int top=0;for(int i=1;i<4;i++)if(seats[i].points>seats[top].points)top=i;seats[top].points+=sticks*1000;sticks=0;message="東風戦終了 / 1位 "+seats[top].name+" "+seats[top].points+"点";revision++;return;}deal(r);}
 public boolean cpu(Random r,java.util.function.IntPredicate controlled){if(phase.equals("result")){boolean changed=false;for(int i=0;i<4;i++)if(controlled.test(i)&&ready.add(i))changed=true;if(allReady()){next(r);return true;}return changed;}if(phase.equals("claim")){for(int i:responders)if(!claims.containsKey(i)&&controlled.test(i)){var opts=options(i);String choice=opts.contains("ron")?"ron":"pass";if(choice.equals("pass")&&!seats[i].reach&&opts.contains("pon")&&(lastTile>=31||r.nextInt(5)==0))choice="pon";action(i,choice,0,r);return true;}return false;}if(!phase.equals("draw")||!controlled.test(turn))return false;var s=seats[turn];if(s.drawn>=0&&score(turn,s.drawn,true)!=null){action(turn,"tsumo",0,r);return true;}int discard=s.hand.size()-1;if(!s.reach){double worst=1e9;for(int i=0;i<s.hand.size();i++){int t=s.hand.get(i);double keep=Collections.frequency(s.hand,t)*3+r.nextDouble()*.3;if(t<27){for(int d:new int[]{-2,-1,1,2})if(t+d>=0&&t+d<27&&(t+d)/9==t/9&&s.hand.contains(t+d))keep+=Math.abs(d)==1?2:1;}else if(t>=31||t==27||t==27+(turn-dealer+4)%4)keep+=1;if(keep<worst){worst=keep;discard=i;}}if(closed(s)&&s.points>=1000&&limit-cursor>=4){int t=s.hand.remove(discard);boolean tenpai=!waits(s).isEmpty();s.hand.add(discard,t);if(tenpai){action(turn,"reach",discard,r);return true;}}}action(turn,"discard",discard,r);return true;}
}
