package jp.neonward;
import java.util.*;
import com.google.gson.*;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.fabricmc.fabric.api.event.player.UseEntityCallback;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.commands.Commands;
import net.minecraft.server.level.*;
import net.minecraft.world.level.Level;
import com.mojang.brigadier.arguments.IntegerArgumentType;
public final class ParlorGames {
 public static class Bet {public String id,name;public boolean even;public int stake=100;Bet(String id,String name,boolean even){this.id=id;this.name=name;this.even=even;}}
 public static class DiceRound {public String phase="bet",call="さあ、張った張った！ 丁か半か！";public long until;public int a=1,b=1;public List<Bet> bets=new ArrayList<>();public int[] cpu={0,1,0};}
 static final Random RANDOM=new java.security.SecureRandom();static final Map<UUID,String> VIEWERS=new HashMap<>();
 static double[] pos(String kind){return switch(kind){case "mahjong"->new double[]{521.5,65,451.5};case "koi"->new double[]{501.5,56,453.5};case "dice"->new double[]{516.5,56,454.5};default->throw new IllegalArgumentException();};}
 static boolean near(ServerPlayer p,String kind){double[] a=pos(kind);return !p.isSpectator()&&p.level().dimension()==Level.OVERWORLD&&p.distanceToSqr(a[0],a[1],a[2])<81;}
 public static void init(){JapaneseParlor.init();net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.SERVER_STARTED.register(s->VIEWERS.clear());
  CommandRegistrationCallback.EVENT.register((d,c,e)->{var root=Commands.literal("parlor");for(String kind:new String[]{"mahjong","koi","dice"}){var game=Commands.literal(kind);for(String action:new String[]{"view","close","join","leave","start","next","discard","reach","tsumo","ron","pon","chi","kan","ankan","pass","play","match","stop","koi","even","odd"})game.then(Commands.literal(action).then(Commands.argument("arg",IntegerArgumentType.integer(-1,1000)).executes(ctx->request(ctx.getSource().getPlayerOrException(),kind,action,IntegerArgumentType.getInteger(ctx,"arg")))));root.then(game);}d.register(root);});
  UseEntityCallback.EVENT.register((p,l,h,e,hit)->{for(String kind:new String[]{"mahjong","koi","dice"})if(e.entityTags().contains("nw_casino_touch_"+kind)){if(p instanceof ServerPlayer sp&&h==net.minecraft.world.InteractionHand.MAIN_HAND)request(sp,kind,"view",0);return net.minecraft.world.InteractionResult.SUCCESS;}return net.minecraft.world.InteractionResult.PASS;});
  net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.DISCONNECT.register((h,s)->VIEWERS.remove(h.player.getUUID()));
  ServerTickEvents.END_SERVER_TICK.register(server->{if(StockMarket.ledger==null)return;long now=server.overworld().getGameTime();if(now%10==0){String before=StockMarket.JSON.toJson(StockMarket.ledger);boolean changed=false;try{var m=StockMarket.ledger.mahjong;var k=StockMarket.ledger.koi;boolean mj=server.getPlayerList().getPlayers().stream().anyMatch(p->near(p,"mahjong")&&m.seat(p.getStringUUID())>=0),kj=server.getPlayerList().getPlayers().stream().anyMatch(p->near(p,"koi")&&k.seat(p.getStringUUID())>=0);if(mj)changed|=m.cpu(RANDOM,i->m.seats[i].cpu||offline(server,m.seats[i].id,"mahjong"));if(kj)changed|=k.cpu(RANDOM,i->k.seats[i].cpu||offline(server,k.seats[i].id,"koi"));changed|=diceTick(now);if(changed)StockMarket.save();}catch(Exception ex){StockMarket.ledger=StockMarket.JSON.fromJson(before,MarketLedger.class);System.err.println("[Parlor] tick rolled back: "+ex);}}
   if(now%10==0){JapaneseParlor.render(server.overworld(),now);for(var p:server.getPlayerList().getPlayers()){String kind=VIEWERS.get(p.getUUID());if(kind!=null&&near(p,kind))send(p,kind,"");}}
  });
 }
 static boolean offline(net.minecraft.server.MinecraftServer server,String id,String kind){if(id.isEmpty()||id.startsWith("cpu:")||id.startsWith("koi-cpu:"))return true;var p=server.getPlayerList().getPlayer(UUID.fromString(id));return p==null||!near(p,kind);}
 static int request(ServerPlayer p,String kind,String action,int arg){if(action.equals("close")){VIEWERS.remove(p.getUUID());return 1;}if(!near(p,kind)||StockMarket.ledger==null)return 0;VIEWERS.put(p.getUUID(),kind);String before=StockMarket.JSON.toJson(StockMarket.ledger),error="";try{
  if(!action.equals("view")){var ledger=StockMarket.ledger;if(kind.equals("mahjong")){var g=ledger.mahjong;if(action.equals("join"))g.join(p.getStringUUID(),p.getName().getString());else if(action.equals("leave")){int i=g.seat(p.getStringUUID());if(i>=0&&(g.phase.equals("lobby")||g.phase.equals("end")))g.seats[i]=new MahjongRound.Seat();else throw new IllegalArgumentException("対局中は席を保持します。画面は閉じられます");}else g.action(g.seat(p.getStringUUID()),action,arg,RANDOM);}else if(kind.equals("koi")){var g=ledger.koi;if(action.equals("join"))g.join(p.getStringUUID(),p.getName().getString());else if(action.equals("leave")){int i=g.seat(p.getStringUUID());if(i>=0&&(g.phase.equals("lobby")||g.phase.equals("end")))g.seats[i]=new KoiRound.Seat();else throw new IllegalArgumentException("対局中は席を保持します");}else g.action(g.seat(p.getStringUUID()),action,arg,RANDOM);}else bet(p,action);StockMarket.save();}
  }catch(Exception ex){StockMarket.ledger=StockMarket.JSON.fromJson(before,MarketLedger.class);error=ex instanceof IllegalArgumentException?ex.getMessage():"保存できなかったため操作を取り消しました";}send(p,kind,error,true);return 1;
 }
 static void bet(ServerPlayer p,String action){if(!action.equals("even")&&!action.equals("odd"))throw new IllegalArgumentException("丁か半を選んでください");var d=StockMarket.ledger.dice;var account=StockMarket.ledger.account(p.getStringUUID());if(!d.phase.equals("bet")||d.bets.size()>=4)throw new IllegalArgumentException("締め切りました。次の勝負をお待ちください");if(d.bets.stream().anyMatch(b->b.id.equals(p.getStringUUID())))throw new IllegalArgumentException("すでに賭けています");if(account.cash<100)throw new IllegalArgumentException("100 Cr必要です");account.cash-=100;d.bets.add(new Bet(p.getStringUUID(),p.getName().getString(),action.equals("even")));if(d.until==0){d.until=p.level().getGameTime()+120;for(int i=0;i<3;i++)d.cpu[i]=RANDOM.nextInt(2);}}
 static boolean diceTick(long now){var d=StockMarket.ledger.dice;if(d.until==0||now<d.until)return false;if(d.phase.equals("bet")){d.phase="closed";d.call="丁半、そろいました！";d.until=now+40;}else if(d.phase.equals("closed")){d.phase="shake";d.call="勝負！ 入ります！";d.until=now+60;}else if(d.phase.equals("shake")){d.a=RANDOM.nextInt(6)+1;d.b=RANDOM.nextInt(6)+1;boolean even=(d.a+d.b)%2==0;for(var b:d.bets)if(b.even==even)StockMarket.ledger.account(b.id).cash+=200;d.phase="reveal";d.call=d.a+"・"+d.b+"の"+(even?"丁！":"半！")+" お見事！";d.until=now+160;}else {d.phase="bet";d.call="さあ、張った張った！ 丁か半か！";d.until=0;d.bets.clear();}return true;}
 static void send(ServerPlayer p,String kind,String error){send(p,kind,error,false);}
 static void send(ServerPlayer p,String kind,String error,boolean open){JsonObject o=new JsonObject();o.addProperty("parlor",kind);o.addProperty("open",open);o.addProperty("cash",StockMarket.ledger.account(p.getStringUUID()).cash);
  if(kind.equals("mahjong")){var g=StockMarket.ledger.mahjong;int me=g.seat(p.getStringUUID());o.addProperty("seat",me);o.addProperty("phase",g.phase);o.addProperty("turn",g.turn);o.addProperty("round",g.round+1);o.addProperty("honba",g.honba);o.addProperty("remaining",Math.max(0,g.limit-g.cursor));o.addProperty("message",error.isEmpty()?g.message:error);o.addProperty("dealer",g.dealer);JsonArray players=new JsonArray();for(int i=0;i<4;i++){var s=g.seats[i];JsonObject v=new JsonObject();v.addProperty("name",s.name);v.addProperty("points",s.points);v.addProperty("reach",s.reach);v.addProperty("count",s.hand.size());v.add("river",StockMarket.JSON.toJsonTree(s.river));v.add("melds",StockMarket.JSON.toJsonTree(s.melds));players.add(v);}o.add("players",players);o.add("hand",StockMarket.JSON.toJsonTree(me>=0?g.seats[me].hand:List.of()));o.add("options",StockMarket.JSON.toJsonTree(me>=0?g.options(me):List.of()));if(!g.wall.isEmpty()){var indicators=new ArrayList<Integer>();for(int i=0;i<=g.kans;i++)indicators.add(g.wall.get(130-i*2));o.add("dora",StockMarket.JSON.toJsonTree(indicators));}}
  else if(kind.equals("koi")){var g=StockMarket.ledger.koi;int me=g.seat(p.getStringUUID());o.addProperty("seat",me);o.addProperty("phase",g.phase);o.addProperty("turn",g.turn);o.addProperty("round",g.round+1);o.addProperty("pending",g.pending);o.addProperty("message",error.isEmpty()?g.message:error);JsonArray players=new JsonArray();for(var s:g.seats){JsonObject v=new JsonObject();v.addProperty("name",s.name);v.addProperty("points",s.points);v.addProperty("count",s.hand.size());v.add("taken",StockMarket.JSON.toJsonTree(s.taken));v.addProperty("yaku",String.join("・",KoiRound.yaku(s.taken).keySet()));players.add(v);}o.add("players",players);o.add("hand",StockMarket.JSON.toJsonTree(me>=0?g.seats[me].hand:List.of()));o.add("field",StockMarket.JSON.toJsonTree(g.field));}
  else {var d=StockMarket.ledger.dice;o.addProperty("phase",d.phase);o.addProperty("message",error.isEmpty()?d.call:error);o.addProperty("a",d.phase.equals("reveal")?d.a:0);o.addProperty("b",d.phase.equals("reveal")?d.b:0);o.addProperty("bets",d.bets.size());o.addProperty("cpu",4-d.bets.size());}
  ServerPlayNetworking.send(p,new StockMarket.Snapshot(o.toString()));
 }
}