package jp.neonward;

import java.util.*;
import java.nio.file.*;
import com.google.gson.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.network.chat.Component;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;

public class PhoneAppScreen extends Screen {
 int selectedFloor,floorPage,selectedLand=-1;boolean floorPicking,landPicking,sellConfirm;
 final int app;int x,y,w,h,page,contactPage,ticks,detailPage;boolean requested,picking,confirm,busy;long sentAt,saleRevision;JsonObject data=new JsonObject();String target="",targetName="",draft="",photo="",notice="",detail="",nonce="";EditBox input;Map<String,PhotoStore.Picture> pictures=new HashMap<>();List<Path> recordings=List.of();int recordIndex;boolean deleting;
 PhoneAppScreen(int app){super(Component.literal("NEON LINK / "+PhoneScreen.APPS[app]));this.app=app;picking=app==1||app==2||app==7;}
 @Override public boolean isPauseScreen(){return false;}
 String text(String k){return data.has(k)?data.get(k).getAsString():"";}
 JsonArray rows(){return data.has("rows")?data.getAsJsonArray("rows"):new JsonArray();}
 JsonArray friends(){return data.has("friends")?data.getAsJsonArray("friends"):new JsonArray();}
 void request(String action){JsonObject o=new JsonObject();o.addProperty("action",action);if(action.endsWith("_sell"))o.addProperty("housing_revision",saleRevision);if(action.equals("land_buy"))o.addProperty("plot",selectedLand);if(action.equals("city_buy"))o.addProperty("floor",selectedFloor);o.addProperty("app",String.valueOf(app));o.addProperty("target",target);o.addProperty("page",page);send(o);}
 void send(JsonObject o){if(!ClientPlayNetworking.canSend(PhoneServices.Request.TYPE)){notice="このサーバーではスマホ機能を利用できません";return;}if(!o.has("app"))o.addProperty("app",String.valueOf(app));if(!o.has("page"))o.addProperty("page",page);if(!o.has("target"))o.addProperty("target",target);if(!o.get("action").getAsString().equals("view")){busy=true;sentAt=System.currentTimeMillis();}ClientPlayNetworking.send(new PhoneServices.Request(o.toString()));}
 void action(String a,String key,String value){var o=new JsonObject();o.addProperty("action",a);o.addProperty(key,value);send(o);}
 void indexAction(String a,int i){var o=new JsonObject();o.addProperty("action",a);o.addProperty("index",i);send(o);}
 void receive(JsonObject o){if(!o.get("app").getAsString().equals(String.valueOf(app)))return;data=o;if(o.has("land_page")&&o.get("land_page").getAsBoolean()){page=2;landPicking=false;floorPicking=false;confirm=false;}if(!text("message").isEmpty())notice=text("message");if(!text("action").equals("view")){busy=false;if(o.get("ok").getAsBoolean()){confirm=false;sellConfirm=false;nonce="";if(text("action").equals("post")||text("action").equals("talk")){draft="";if(input!=null)input.setValue("");photo="";}if(text("action").equals("delete"))detail="";}}
  if(app==3){pictures.values().forEach(PhotoStore.Picture::close);pictures.clear();for(var v:rows()){var r=v.getAsJsonObject();String s=r.get("photo").getAsString();if(!s.isEmpty())try{pictures.put(r.get("id").getAsString(),new PhotoStore.Picture(Base64.getDecoder().decode(s)));}catch(Exception ignored){}}}rebuildWidgets();}
 void button(int xx,int yy,int ww,String label,Runnable r){addRenderableWidget(new PhoneScreen.NeonButton(xx,yy,ww,19,label,b->{if(!busy)r.run();}));}
 void edit(int yy,int ww,int max){if(input!=null)draft=input.getValue();input=new EditBox(font,x+12,yy,ww,20,Component.literal(app==7?"送金額":app==2?"メッセージ":"投稿本文"));input.setMaxLength(max);input.setValue(draft);addRenderableWidget(input);}
 int contactRows(){return Math.max(1,Math.min(4,(h-145)/34));}
 int questRows(){return Math.max(1,Math.min(3,(h-139)/47));}
 int chatRows(){return h>=300?2:1;}
 void refresh(){rebuildWidgets();}
 void choose(){picking=true;confirm=false;page=0;rebuildWidgets();}
 @Override protected void init(){w=Math.min(460,width-16);h=Math.min(330,height-12);x=(width-w)/2;y=(height-h)/2;if(!requested){requested=true;request("view");if(app==1)PhoneAudio.command("view");}if(app==6)recordings=PhoneAudio.files();recordIndex=Math.min(recordIndex,Math.max(0,recordings.size()-1));
  button(x+12,y+h-25,w-24,"スマホへ戻る",()->onClose());
  if(app==6){button(x+12,y+57,110,PhoneAudio.recording?"停止して保存":"録音開始（マイクON）",()->{if(PhoneAudio.recording)PhoneAudio.stopCapture();else PhoneAudio.record();rebuildWidgets();});button(x+128,y+57,80,"再生停止",()->PhoneAudio.stopOutput());if(!recordings.isEmpty()){button(x+12,y+133,40,"<",()->{recordIndex=Math.max(0,recordIndex-1);deleting=false;rebuildWidgets();});button(x+58,y+133,40,">",()->{recordIndex=Math.min(recordings.size()-1,recordIndex+1);deleting=false;rebuildWidgets();});button(x+105,y+133,80,"再生",()->PhoneAudio.play(recordings.get(recordIndex)));button(x+191,y+133,100,deleting?"削除を確定":"削除",()->{if(deleting){try{PhoneAudio.stopOutput();Files.delete(recordings.get(recordIndex));}catch(Exception e){notice="録音を削除できません";}deleting=false;}else deleting=true;rebuildWidgets();});}return;}
  if(app==1&&!PhoneAudio.state.equals("idle")){if(PhoneAudio.state.equals("incoming"))button(x+12,y+111,135,"応答（マイクON）",()->PhoneAudio.command("accept"));if(PhoneAudio.state.equals("active")){button(x+12,y+111,135,PhoneAudio.muted?"マイクをON":"ミュート",()->{PhoneAudio.muted=!PhoneAudio.muted;rebuildWidgets();});button(x+155,y+111,44,"音量−",()->{PhoneAudio.adjustVolume(-.25f);rebuildWidgets();});button(x+203,y+111,44,"音量＋",()->{PhoneAudio.adjustVolume(.25f);rebuildWidgets();});}button(x+w-135,y+111,120,"通話を終了",()->PhoneAudio.command("end"));return;}
  if(picking){var f=friends();for(int j=0;j<contactRows();j++){int i=contactPage*contactRows()+j;if(i>=f.size())break;var r=f.get(i).getAsJsonObject();button(x+w-99,y+63+j*34,85,app==1?"電話する":"選択",()->{target=r.get("id").getAsString();targetName=r.get("name").getAsString();picking=false;page=0;detail="";data.remove("rows");if(app==1){PhoneAudio.command("dial "+target);}else request("view");rebuildWidgets();});}button(x+12,y+h-79,38,"<",()->{contactPage=Math.max(0,contactPage-1);rebuildWidgets();});button(x+56,y+h-79,38,">",()->{contactPage=Math.min(Math.max(0,(friends().size()-1)/contactRows()),contactPage+1);rebuildWidgets();});button(x+100,y+h-79,100,"フレンドを追加",()->minecraft.gui.setScreen(new FriendsScreen()));return;}
  if(app==2){button(x+w-107,y+30,94,"相手を変更",()->choose());edit(y+h-81,w-97,180);button(x+w-78,y+h-81,65,"送信",()->action("talk","text",input.getValue()));button(x+12,y+h-108,35,"<",()->{page=Math.min(Math.max(0,(rows().size()-1)/chatRows()),page+1);rebuildWidgets();});button(x+52,y+h-108,35,">",()->{page=Math.max(0,page-1);rebuildWidgets();});}
  else if(app==3){if(!detail.isEmpty()){button(x+12,y+h-79,80,"一覧に戻る",()->{detail="";confirm=false;rebuildWidgets();});button(x+98,y+h-79,60,"本文続き",()->{detailPage++;rebuildWidgets();});for(var v:rows()){var r=v.getAsJsonObject();if(r.get("id").getAsString().equals(detail)&&r.get("own").getAsBoolean())button(x+w-124,y+h-79,110,confirm?"削除を確定":"この投稿を削除",()->{if(confirm)action("delete","target",detail);else {confirm=true;rebuildWidgets();}});}return;}int rh=Math.max(24,Math.min(60,(h-158)/2));for(int j=0;j<rows().size();j++){var r=rows().get(j).getAsJsonObject();String id=r.get("id").getAsString();int yy=y+54+j*rh;button(x+w-123,yy,52,(r.get("liked").getAsBoolean()?"♥ ":"♡ ")+r.get("likes").getAsInt(),()->action("like","target",id));button(x+w-66,yy,52,"見る",()->{detail=id;detailPage=0;rebuildWidgets();});}
   button(x+12,y+h-110,30,"<",()->{page=Math.min(Math.max(0,data.has("pages")?data.get("pages").getAsInt()-1:0),page+1);request("view");});button(x+46,y+h-110,30,">",()->{page=Math.max(0,page-1);request("view");});button(x+82,y+h-110,110,photo.isEmpty()?"写真を選ぶ":"添付を取り消す",()->{if(photo.isEmpty())minecraft.gui.setScreen(new PhonePhotoPicker(this));else {photo="";rebuildWidgets();}});edit(y+h-81,w-98,180);button(x+w-78,y+h-81,65,"投稿",()->{var o=new JsonObject();o.addProperty("action","post");o.addProperty("text",input.getValue());o.addProperty("photo",photo);page=0;send(o);});}
  else if(app==7){button(x+w-107,y+30,94,"相手を変更",()->{confirm=false;choose();});edit(y+91,w-140,7);button(x+w-116,y+91,102,confirm?"送金を確定":"金額を確認",()->{if(!confirm){try{long n=Long.parseLong(input.getValue());if(n<1||n>1000000)throw new Exception();confirm=true;nonce=UUID.randomUUID().toString();notice=targetName+"へ "+n+" Cr 送ります";rebuildWidgets();}catch(Exception e){notice="1～1,000,000の整数を入力してください";}}else{var o=new JsonObject();o.addProperty("action","transfer");o.addProperty("amount",Long.parseLong(draft));o.addProperty("nonce",nonce);send(o);}});if(confirm)input.setEditable(false);}
  else if(app==8){
   if(page%3==2){landWidgets();return;}
   String homeKey=page%3==0?"city":"home";boolean ownsHome=data.has(homeKey)&&data.get(homeKey).getAsInt()>0;
   if(ownsHome){
    floorPicking=false;confirm=false;
    button(x+12,y+63,w-24,page%3==0?text("city")+"階 / 所有中":"HIDEOUT / 所有中",()->{});
    button(x+12,y+h-106,w-24,sellConfirm?"回収済み・売却を確定":(page%3==0?"20,000":"10,000")+" Cr で売却",()->{if(sellConfirm)request(page%3==0?"city_sell":"home_sell");else{sellConfirm=true;saleRevision=data.get("housing_revision").getAsLong();notice="家具・収納は事前回収 / 自動回収はありません";rebuildWidgets();}});
    button(x+98,y+h-79,w-110,sellConfirm?"売却をキャンセル":"入口を地図で確認",()->{if(sellConfirm){sellConfirm=false;notice="";rebuildWidgets();}else if(page%3==0)map(108,237,false);else map(221,949,true);});
    button(x+12,y+h-79,35,"<",()->{page=(page+2)%3;sellConfirm=false;notice="";rebuildWidgets();});button(x+53,y+h-79,35,">",()->{page=(page+1)%3;sellConfirm=false;notice="";rebuildWidgets();});return;
   }
   if(floorPicking){int count=Math.max(1,Math.min(5,(h-145)/24))*3;var floors=data.has("city_floors")?data.getAsJsonArray("city_floors"):new JsonArray();for(int j=0;j<count;j++){int i=floorPage*count+j;if(i>=floors.size())break;var f=floors.get(i).getAsJsonObject();int n=f.get("floor").getAsInt();boolean free=f.get("vacant").getAsBoolean();var btn=new PhoneScreen.NeonButton(x+12+(j%3)*(w-24)/3,y+59+(j/3)*24,(w-30)/3,19,n+"階 / "+(free?"空室":"入居済"),v->{if(!busy&&free){selectedFloor=n;confirm=true;floorPicking=false;notice=n+"階 / 20,000 Cr を購入します";rebuildWidgets();}});btn.active=free;addRenderableWidget(btn);}button(x+12,y+h-79,35,"<",()->{floorPage=Math.max(0,floorPage-1);rebuildWidgets();});button(x+53,y+h-79,35,">",()->{floorPage=Math.min(Math.max(0,(floors.size()-1)/count),floorPage+1);rebuildWidgets();});button(x+98,y+h-79,w-110,"物件に戻る",()->{floorPicking=false;confirm=false;rebuildWidgets();});return;}
   String[] labels={"街の専有フロア / 20,000 Cr","HIDEOUT / 10,000 Cr","西側の土地 / 20,000 Cr"};String[] actions={"city_buy","home_buy","land_buy"};button(x+12,y+63,w-24,labels[page%3],()->{if(page%3==0){floorPicking=true;confirm=false;request("view");rebuildWidgets();}});button(x+12,y+h-106,w-24,page%3==0?(confirm?selectedFloor+"階の購入を確定":"空いている階を選ぶ"):(confirm?"購入を確定":"この物件を購入"),()->{if(confirm)request(actions[page%3]);else if(page%3==0){floorPicking=true;request("view");rebuildWidgets();}else{confirm=true;rebuildWidgets();}});button(x+98,y+h-79,w-110,"入口を地図で確認",()->{if(page%3==0)map(108,237,false);else if(page%3==1)map(221,949,true);else map(-100,154,false);});button(x+12,y+h-79,35,"<",()->{page=(page+2)%3;confirm=false;rebuildWidgets();});button(x+53,y+h-79,35,">",()->{page=(page+1)%3;confirm=false;rebuildWidgets();});}


  else if(app==9||app==10){for(int j=0;j<questRows();j++){int i=page*questRows()+j;if(i>=rows().size())break;var r=rows().get(i).getAsJsonObject();int yy=y+54+j*47;boolean allowed=r.get("unlocked").getAsBoolean();if(app==9){boolean a=r.get("accepted").getAsBoolean();if(a)button(x+w-86,yy,73,detail.equals("cancel"+i)?"取消確定":"受注取消",()->{if(detail.equals("cancel"+i)){indexAction("quest_cancel",i);detail="";}else{detail="cancel"+i;rebuildWidgets();}});else if(allowed)button(x+w-86,yy,73,"受注",()->indexAction("quest_accept",i));}else if(allowed)button(x+w-86,yy,73,"設定",()->indexAction("title",i));}
   button(x+12,y+h-79,35,"<",()->{page=Math.max(0,page-1);detail="";rebuildWidgets();});button(x+52,y+h-79,35,">",()->{page=Math.min(Math.max(0,(rows().size()-1)/questRows()),page+1);detail="";rebuildWidgets();});if(app==9)button(x+100,y+h-79,125,"報告・昇級は企業受付",()->map(83,115,false));}
 }
 void landWidgets(){
  if(landPicking){
   var plots=data.has("land_plots")?data.getAsJsonArray("land_plots"):new JsonArray();
   for(int i=0;i<plots.size();i++){var row=plots.get(i).getAsJsonObject();int n=row.get("plot").getAsInt();boolean free=row.get("vacant").getAsBoolean();
    var btn=new PhoneScreen.NeonButton(x+12+(i%2)*(w-24)/2,y+59+(i/2)*24,(w-30)/2,19,"土地"+(n+1)+" / "+(free?"空き":row.get("mine").getAsBoolean()?"所有中":row.get("owner").getAsString()),b->{if(!busy&&free){selectedLand=n;landPicking=false;confirm=true;notice="土地"+(n+1)+" / 20,000 Cr を購入します";rebuildWidgets();}});
    btn.active=free;addRenderableWidget(btn);
   }
   button(x+12,y+h-79,w-24,"土地案内に戻る",()->{landPicking=false;confirm=false;rebuildWidgets();});return;
  }
  button(x+12,y+63,w-24,"西側の土地 / 20,000 Cr",()->{confirm=false;landPicking=true;request("view");rebuildWidgets();});
  button(x+12,y+h-106,w-24,confirm?"土地"+(selectedLand+1)+"の購入を確定":"空いている土地を選ぶ",()->{if(confirm)request("land_buy");else{landPicking=true;request("view");rebuildWidgets();}});
  button(x+98,y+h-79,w-110,"西門の先を地図で確認",()->map(-100,154,false));
  button(x+12,y+h-79,35,"<",()->{page=1;confirm=false;rebuildWidgets();});
  button(x+53,y+h-79,35,">",()->{page=0;confirm=false;rebuildWidgets();});
 }
 void map(double xx,double zz,boolean slum){var m=new CityMapScreen();m.initialized=true;m.follow=false;m.slum=slum;m.cx=xx;m.cz=zz;m.zoom=5;minecraft.gui.setScreen(m);}
 @Override public void tick(){super.tick();if(busy&&System.currentTimeMillis()-sentAt>7000){busy=false;notice="応答を確認できません。更新して残高・履歴を確認してください";rebuildWidgets();}if(++ticks%100==0&&!busy&&!confirm&&!sellConfirm&&detail.isEmpty()&&(app!=3||draft.isEmpty()))request("view");if(app==6&&ticks%20==0)rebuildWidgets();}
 @Override public void onClose(){minecraft.gui.setScreen(new PhoneScreen());}
 @Override public void removed(){if(input!=null)draft=input.getValue();pictures.values().forEach(PhotoStore.Picture::close);pictures.clear();if(app==6&&PhoneAudio.state.equals("idle")){if(PhoneAudio.recording)PhoneAudio.stopCapture();PhoneAudio.stopOutput();}}
 void line(GuiGraphicsExtractor g,String s,int xx,int yy,int color){g.text(font,font.plainSubstrByWidth(s,Math.max(1,w-(xx-x)-14)),xx,yy,color);}
 void wrap(GuiGraphicsExtractor g,String s,int xx,int yy,int width,int max){int i=0;while(!s.isEmpty()&&i<max){String part=font.plainSubstrByWidth(s,width);if(part.isEmpty())break;g.text(font,part,xx,yy+i*11,0xffd2e9ef);s=s.substring(part.length());i++;}}
 void postBody(GuiGraphicsExtractor g,String text,int yy,int max){var lines=new ArrayList<String>();while(!text.isEmpty()){String part=font.plainSubstrByWidth(text,w-24);if(part.isEmpty())break;lines.add(part);text=text.substring(part.length());}int pages=Math.max(1,(lines.size()+max-1)/max);detailPage%=pages;for(int i=0;i<max&&detailPage*max+i<lines.size();i++)g.text(font,lines.get(detailPage*max+i),x+12,yy+i*11,0xffd2e9ef);}
 String date(JsonObject r){return java.time.Instant.ofEpochMilli(r.get("time").getAsLong()).atZone(java.time.ZoneId.systemDefault()).format(java.time.format.DateTimeFormatter.ofPattern("MM/dd HH:mm"));}
 @Override public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float dt){g.fill(x-4,y-3,x+w+4,y+h+3,0xff060b13);g.outline(x-4,y-3,w+8,h+6,0xff355468);g.fill(x,y,x+w,y+h,0xff0b1422);for(int yy=y+29;yy<y+h-32;yy+=5)g.fill(x+2,yy,x+w-2,yy+1,0xff102031);g.fill(x,y+5,x+3,y+70,0xff5bf7e7);g.fill(x+w-3,y+h-73,x+w,y+h-6,0xffff51af);line(g,"NEON LINK / "+PhoneScreen.APPS[app],x+12,y+11,0xff77fff0);
  if(app==6){line(g,"VOICE MEMO / このPCに保存・最大2分",x+12,y+35,0xffa9bdce);line(g,PhoneAudio.recording?"● REC "+(System.currentTimeMillis()-PhoneAudio.recordingAt)/1000+"秒 / マイク使用中":"○ 録音停止",x+12,y+88,0xffff74b6);line(g,recordings.isEmpty()?"まだ録音がありません":recordings.get(recordIndex).getFileName().toString(),x+12,y+113,0xffd7f4f0);line(g,"画面を閉じると録音を停止して保存します",x+12,y+168,0xff9dbbcc);notice=PhoneAudio.error.isEmpty()?PhoneAudio.message:PhoneAudio.error;}
  else if(app==1&&!PhoneAudio.state.equals("idle")){line(g,PhoneAudio.name,x+12,y+51,0xffe6fff8);line(g,PhoneAudio.message,x+12,y+76,0xff9cded8);line(g,"通話音量："+Math.round(PhoneAudio.callGain*100/2f)+"% / 音量−・音量＋で調整",x+12,y+151,0xffb5ccda);line(g,"応答後はマイクがON。スマホを閉じても通話できます",x+12,y+168,0xffb5ccda);line(g,PhoneAudio.error,x+12,y+188,0xffff9f94);}
  else if(picking){line(g,app==1?"発信すると応答後にマイクを使用します":"フレンドから相手を選んでください",x+12,y+35,0xffa9ccd8);if(friends().isEmpty())line(g,"フレンドを追加すると利用できます",x+12,y+85,0xffd8e4eb);for(int j=0;j<contactRows();j++){int i=contactPage*contactRows()+j;if(i>=friends().size())break;var f=friends().get(i).getAsJsonObject();g.text(font,font.plainSubstrByWidth(f.get("name").getAsString(),w-128),x+18,y+68+j*34,0xffd5fff4);}if(app==1)line(g,PhoneAudio.error.isEmpty()?PhoneAudio.message:PhoneAudio.error,x+12,y+h-100,0xffffbf94);}
  else if(app==2){line(g,"TO / "+targetName,x+12,y+35,0xff73e8dd);int count=rows().size(),start=Math.max(0,count-chatRows()-page*chatRows()),end=Math.max(0,count-page*chatRows());for(int i=start;i<end;i++){var r=rows().get(i).getAsJsonObject();int yy=y+57+(i-start)*67;g.fill(x+10,yy,x+w-10,yy+63,r.get("own").getAsBoolean()?0xff173b40:0xff1c273c);line(g,r.get("name").getAsString()+" / "+date(r),x+18,yy+4,0xff7be6d6);wrap(g,r.get("text").getAsString(),x+18,yy+16,w-36,4);}if(count==0)line(g,"最初のメッセージを送ろう",x+12,y+70,0xffbacfd9);}
  else if(app==3){if(!detail.isEmpty()){for(var v:rows()){var r=v.getAsJsonObject();if(!r.get("id").getAsString().equals(detail))continue;line(g,r.get("name").getAsString()+" / "+date(r),x+12,y+35,0xff75f2df);var picture=pictures.get(detail);int ph=h>=300?80:35;if(picture!=null)picture.draw(g,x+12,y+52,w-24,ph);postBody(g,r.get("text").getAsString(),y+57+(picture==null?0:ph),Math.max(1,(h-141-(picture==null?0:ph))/11));if(r.get("own").getAsBoolean()&&!confirm){/* Delete is exposed through the explicit button below, not by clicking the image. */}}}else{line(g,"街のみんなに公開 / 最新の投稿",x+12,y+34,0xffb0c6d4);int rh=Math.max(24,Math.min(60,(h-158)/2));for(int i=0;i<rows().size();i++){var r=rows().get(i).getAsJsonObject();int yy=y+54+i*rh;var pic=pictures.get(r.get("id").getAsString());if(pic!=null)pic.draw(g,x+12,yy,32,rh-3);int xx=x+(pic==null?12:49);g.text(font,font.plainSubstrByWidth(r.get("name").getAsString()+"  "+date(r),Math.max(1,w-xx+x-130)),xx,yy+2,0xff77f0df);g.text(font,font.plainSubstrByWidth(r.get("text").getAsString(),Math.max(1,w-xx+x-130)),xx,yy+14,0xffd6e2ed);}if(!photo.isEmpty())line(g,"写真添付あり",x+200,y+h-105,0xffff83bf);}}
  else if(app==7){line(g,"残高 / "+text("cash")+" Cr",x+12,y+35,0xff82ffe0);line(g,"送金先："+targetName,x+12,y+66,0xffd9f3f0);line(g,"最近の入出金",x+12,y+131,0xff83b6cd);int start=Math.max(0,rows().size()-4);for(int i=start;i<rows().size()&&149+(i-start)*17<h-80;i++){var r=rows().get(i).getAsJsonObject();line(g,(r.get("own").getAsBoolean()?"→ "+r.get("toName").getAsString():"← "+r.get("name").getAsString())+" / "+r.get("text").getAsString(),x+12,y+149+(i-start)*17,0xffc3e8e5);}}
  else if(app==8&&page%3==2){line(g,landPicking?"購入する土地を選択 / 20,000 Cr":"残高 / "+text("cash")+" Cr",x+12,y+35,0xff83ffdd);if(!landPicking)line(g,"所有地 "+text("land")+"区画 / 32×32 / 建築・農業用",x+12,y+91,0xffd7fff7);}
  else if(app==8&&floorPicking){line(g,"希望の階を選択 / 入居済みの階は選べません",x+12,y+35,0xff83ffdd);}
  else if(app==8){line(g,"残高 / "+text("cash")+" Cr",x+12,y+35,0xff83ffdd);String key=page%3==0?"city":page%3==1?"home":"land";line(g,text(key).equals("0")?(page%3==0&&text("city_free").equals("0")?"満室":"販売中 / 他の購入者と重複しません"):page%3==0?text(key)+"階を所有 / 1階は共用受付":"あなた専用の区画 #"+text(key),x+12,y+91,0xffd7fff7);}

  else if(app==9||app==10){line(g,app==9?"RANK "+(data.has("rank")?GuildRanks.NAMES[data.get("rank").getAsInt()]:"F")+" / "+text("exam"):"現在の称号 / "+text("title"),x+12,y+34,0xff8ae9db);for(int j=0;j<questRows();j++){int i=page*questRows()+j;if(i>=rows().size())break;var r=rows().get(i).getAsJsonObject();int yy=y+54+j*47;g.fill(x+10,yy,x+w-10,yy+43,0xff152a3b);g.text(font,font.plainSubstrByWidth(r.get("title").getAsString(),w-110),x+15,yy+4,0xffdefcf5);line(g,r.get("detail").getAsString(),x+15,yy+18,0xffa4c1d0);line(g,app==9?(r.get("accepted").getAsBoolean()?"進行 "+r.get("progress").getAsInt()+" / "+r.get("goal").getAsInt():r.get("unlocked").getAsBoolean()?"受注可能":"ランク未達")+" / 報酬 "+r.get("reward").getAsInt()+" Cr":r.get("unlocked").getAsBoolean()?"獲得済み":"未獲得",x+15,yy+30,0xffffc98b);}}
  line(g,busy?"処理中…":notice,x+12,y+h-49,0xffffc58c);super.extractRenderState(g,mx,my,dt);
 }
}
