package jp.neonward;
import java.util.*;
import com.google.gson.*;
import com.mojang.brigadier.arguments.StringArgumentType;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.networking.v1.*;
import net.minecraft.commands.Commands;
import net.minecraft.server.level.ServerPlayer;
public final class PhoneFriends {
 static MarketLedger.Account prepare(ServerPlayer p){var a=StockMarket.ledger.account(p.getStringUUID());a.profileName=p.getGameProfile().name();return a;}
 static boolean linked(MarketLedger l,String who,String other){var a=l.accounts.get(who);var b=l.accounts.get(other);return a!=null&&b!=null&&a.friends.contains(other)&&b.friends.contains(who);}
 static String change(MarketLedger l,String who,String action,String other){var a=l.account(who);var b=l.accounts.get(other);if(who.equals(other))return "自分自身は追加できません";if(b==null)return "プレイヤーが見つかりません";
 if(action.equals("request")){if(linked(l,who,other))return "登録済みです";if(a.friends.size()>=100||b.friends.size()>=100||b.friendRequests.size()>=100)return "登録できる人数の上限です";b.friendRequests.add(who);return "フレンド申請を送りました";}
 if(action.equals("accept")){if(!a.friendRequests.contains(other))return "申請が見つかりません";if(a.friends.size()>=100||b.friends.size()>=100)return "フレンドの上限です";a.friendRequests.remove(other);b.friendRequests.remove(who);a.friends.add(other);b.friends.add(who);return "フレンドになりました。プロフィールを開けます";}
 if(action.equals("decline")){a.friendRequests.remove(other);return "申請を取り消しました";}
 if(action.equals("remove")){a.friends.remove(other);b.friends.remove(who);a.friendRequests.remove(other);b.friendRequests.remove(who);return "フレンド登録を解除しました";}return "操作を確認してください";}
 static JsonObject profile(MarketLedger l,String who,String id,boolean online){if(!who.equals(id)&&!linked(l,who,id))return null;var a=l.accounts.get(id);if(a==null)return null;var o=new JsonObject();o.addProperty("id",id);o.addProperty("name",a.profileName);o.addProperty("status",a.profileStatus);o.addProperty("title",PhoneServices.title(a));o.addProperty("rank",GuildRanks.rank(a));o.addProperty("reports",a.guildRankReports);o.addProperty("exam",a.guildExamActive);o.addProperty("online",online);return o;}
 static void init(){CommandRegistrationCallback.EVENT.register((d,c,e)->{var root=Commands.literal("neonfriends").executes(ctx->request(ctx.getSource().getPlayerOrException(),"view",""));root.then(Commands.literal("view").executes(ctx->request(ctx.getSource().getPlayerOrException(),"view","")));for(String a:List.of("request","accept","decline","remove","profile"))root.then(Commands.literal(a).then(Commands.argument("target",StringArgumentType.word()).executes(ctx->request(ctx.getSource().getPlayerOrException(),a,StringArgumentType.getString(ctx,"target")))));root.then(Commands.literal("status").then(Commands.argument("text",StringArgumentType.greedyString()).executes(ctx->request(ctx.getSource().getPlayerOrException(),"status",StringArgumentType.getString(ctx,"text")))));d.register(root);});
 ServerPlayConnectionEvents.JOIN.register((h,s,server)->{if(StockMarket.ledger!=null){var a=prepare(h.player);try{StockMarket.save();}catch(Exception ex){System.err.println("[Friends] profile name not saved");}}});}
 static int request(ServerPlayer p,String action,String target){if(StockMarket.ledger==null||p.isSpectator()||PhoneEquipment.get(p).isEmpty())return 0;String before=StockMarket.JSON.toJson(StockMarket.ledger),message="申請が承認されるとプロフィールが見られます",selected="";String who=p.getStringUUID();try{var a=prepare(p);for(var player:p.level().getServer().getPlayerList().getPlayers())prepare(player);
 if(action.equals("status")){String clean=target.replaceAll("[\\p{Cntrl}]","").strip();if(clean.codePointCount(0,clean.length())>48)message="ひとことは48文字までです";else {a.profileStatus=clean;message="ひとことを保存しました";selected=who;}}
 else if(!action.equals("view")){String id=target;try{UUID.fromString(id);}catch(Exception ex){var other=p.level().getServer().getPlayerList().getPlayerByName(target);if(other==null)throw new IllegalArgumentException("相手は同じサーバーにいる人から選んでね");id=other.getStringUUID();}if(action.equals("profile")){if(profile(StockMarket.ledger,who,id,false)==null)throw new IllegalArgumentException("フレンドだけがプロフィールを見られます");selected=id;}else message=change(StockMarket.ledger,who,action,id);}
 StockMarket.save();}catch(Exception ex){StockMarket.ledger=StockMarket.JSON.fromJson(before,MarketLedger.class);message=ex instanceof IllegalArgumentException?ex.getMessage():"保存できなかったため変更を取り消しました";selected="";}send(p,selected,message);return 1;}
 static void send(ServerPlayer p,String selected,String msg){var l=StockMarket.ledger;var a=l.account(p.getStringUUID());var server=p.level().getServer();var o=new JsonObject();o.addProperty("friends_ui",true);o.addProperty("message",msg);o.addProperty("self",p.getStringUUID());o.addProperty("status",a.profileStatus);var friends=new JsonArray();for(String id:a.friends)if(linked(l,p.getStringUUID(),id)){var v=profile(l,p.getStringUUID(),id,server.getPlayerList().getPlayer(UUID.fromString(id))!=null);friends.add(v);}o.add("friends",friends);
 var pending=new JsonArray();for(String id:a.friendRequests){var b=l.accounts.get(id);if(b!=null){var v=new JsonObject();v.addProperty("id",id);v.addProperty("name",b.profileName);pending.add(v);}}o.add("pending",pending);var online=new JsonArray();for(var other:server.getPlayerList().getPlayers()){String id=other.getStringUUID();if(id.equals(p.getStringUUID())||a.friends.contains(id))continue;var v=new JsonObject();v.addProperty("id",id);v.addProperty("name",other.getGameProfile().name());v.addProperty("sent",l.account(id).friendRequests.contains(p.getStringUUID()));online.add(v);}o.add("online",online);
 if(!selected.isEmpty()){var v=profile(l,p.getStringUUID(),selected,server.getPlayerList().getPlayer(UUID.fromString(selected))!=null);if(v!=null)o.add("profile",v);}ServerPlayNetworking.send(p,new StockMarket.Snapshot(o.toString()));}
}
